[tool.poetry]
name = "copilot"
version = "0.1.0"
description = ""
authors = ["Aditya Gudimella <aditya.gudimella@microsoft.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
